### PR TITLE
Iamtesch/proposed v1.1

### PR DESCRIPTION
**Pull request by iamtesch**
I think this is reasonably complete/readable -- is there anything in here anyone would like to change or clarify before we make this public?

### CODE REVIEW

**Comment by ennerf** [comment]
had change-requests, but accidentally approved them. I can't find a way to un-approve.

**Comment by iamtesch** [comment]
@ennerf -- thanks for the review.  A couple of thoughts:

> Maybe call Format->Types "Primitives" and add a content table on top to skip to the more interesting Robot Elements parts.

I love the idea of adding a content table on top -- I'll do that.

Regarding "primatives" -- I actually see these as more of a "type" associated with particular attributes; I think that's the notation that I've seen in XML, but I could be wrong.  Should we table that discussion for the future, or do you feel strongly about this one now?

> Who is the primary audience? People who implement the spec, or users who want to find out capabilities beyond the examples? If the later, I'd suggest moving the type definition somewhere on the bottom. Starting with the types makes it look more complex than it is.

I'm trying to make this a comprehensive spec for both purposes.  Therefore I value completeness, but readability is a concern as well.  I think that most users will just use the examples, though, and not look at this, so I'd prefer it as a definitive technical reference vs. a "getting started" guide.

> Should the "robot" element (and version string?) be described first? The examples may be clearer if e.g. actuator would be inside a robot element, so that the examples are actually valid and parseable.

Perhaps -- I had not done this, only because I didn't want to introduce dependencies that hadn't been described yet.  This shouldn't be hard to rework though.

> add example for link that uses e.g. pi/2
> add example for overriding mass / com
> add examples for rigid-body element with rotation matrix formula
> add example for joint element

+1

> add example for a whole kit, e.g., 6 dof arm with gripper

The folder is full of whole kit examples, including a 6DOF arm, and the gripper isn't part of the spec.  Do you just want this in the FORMAT file vs. in the directory?

**Comment by ennerf** [comment]
> Regarding "primitives" -- I actually see these as more of a "type" associated with particular attributes; I think that's the notation that I've seen in XML, but I could be wrong. Should we table that discussion for the future, or do you feel strongly about this one now?

I'm not that familiar with the notation, so you're probably right.

> Perhaps -- I had not done this, only because I didn't want to introduce dependencies that hadn't been described yet. This shouldn't be hard to rework though.

I just like having the documentation flow start with the outer-most tag rather than go inside out.

> The folder is full of whole kit examples, including a 6DOF arm, and the gripper isn't part of the spec. Do you just want this in the FORMAT file vs. in the directory?

I was only referring to the Format file. I like having a full example inline with the text rather than having to search through the repo. A table of pictures with links (or the content) to the description could be nice as well (similar to the [Kits ](http://docs.hebi.us/hardware.html#Kits) page on docs).

Overall, all these changes are cosmetic and can be changed later. The content is as far as I can tell correct, so feel free to merge it and punt on the other things for now.

**Comment by iamtesch** [comment]
@ennerf -- ready for re-review

**Comment by iamtesch** [comment]
@ennerf -- don't merge this yet; tracking down one issue with the grammar.  Will have tests tomorrow

**Pull request merged**
